name: ESBMC Action Demo

on: push

jobs:
    run-esbmc-action:
        runs-on: ubuntu-latest
        steps:
            - name: esbmc-action
              id: esbmc-action
              uses: esbmc/esbmc-action@v3
              with:
                files: |
                    cppfile.cpp
                    folder/space file.c
                esbmc-options: --incremental-bmc --witness-output out.txt
                create-artifact: y
            
            - name: access artifact
              run: |
                echo "${{ steps.esbmc-action.outputs.artifact-url }}"
                echo "${{ steps.esbmc-action.outputs.artifact-id }}"