name: ESBMC Action Demo

on: push

jobs:
    run-esbmc-action:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 2
            
            - name: esbmc-action
              uses: esbmc/esbmc-action@v3
              with:
                checkout: n