name: ESBMC Action Demo

on: push

jobs:
    run-esbmc-action:
        runs-on: ubuntu-latest
        steps:
            - name: esbmc-action
              uses: esbmc/esbmc-action@v3
              with:
                files: |
                    cppfile.cpp
                    folder/space file.c
                esbmc-options: --incremental-bmc --witness-output out.txt
                create-artifact: y